export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UPDATE_TRANSACTION_AMOUNT = 'UPDATE_TRANSACTION_AMOUNT';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

